name: Docker Image (pre-release)

on:
  push:
    branches: [ pre-release ]
    
env:
  DOTNET_VERSION: '8.0.100' # The .NET SDK version to use

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Test Cases
    
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: openbudgeteer_test
          MYSQL_USER: openbudgeteer_test
          MYSQL_PASSWORD: openbudgeteer_test
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Install Blazor dependencies
        run: dotnet restore OpenBudgeteer.Blazor
        
      - name: Build Blazor
        run: dotnet build OpenBudgeteer.Blazor --configuration Release --no-restore
        
      - name: Run Core Test Cases
        env:
          CONNECTION_SERVER: mariadb
          CONNECTION_PORT: 3306
          CONNECTION_USER: openbudgeteer_test
          CONNECTION_PASSWORD: openbudgeteer_test
          CONNECTION_DATABASE: openbudgeteer_test
        run: dotnet test OpenBudgeteer.Core.Test
  deploy-docker-app:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image (App)
    needs: test
    if: success()
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: axelander/openbudgeteer:pre-release
          platforms: linux/arm64,linux/amd64
  deploy-docker-api:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image (API)
    needs: test
    if: success()
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: axelander/openbudgeteer-api:pre-release
          file: API.Dockerfile
          platforms: linux/arm64,linux/amd64